services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - venv:/home/vscode/app/.venv
      - uv-cache:/home/vscode/.cache/uv
      - bun-cache:/home/vscode/.bun/install/cache
      - npm-cache:/home/vscode/.npm
      - pip-cache:/home/vscode/.cache/pip
    tty: true
    stdin_open: true

volumes:
  venv:
    driver: local
  uv-cache:
    driver: local
  bun-cache:
    driver: local
  npm-cache:
    driver: local
  pip-cache:
    driver: local
